# Generated by Django 4.0.4 on 2022-05-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isb_number',
            field=models.CharField(max_length=13),
        ),
    ]
