# Generated by Django 4.0.4 on 2022-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
    ]
